#!/usr/bin/env bash
# ==============================================================================
# Script: Generate-DFIRHtmlReport.sh
# Description: Generates standalone interactive HTML Forensic Report for Linux
# Documentation: Parses collected CSV files and forensic evidence generated by DFIR-Script.sh
#                and modular acquisition scripts, generating a standalone, interactive
#                dark-mode HTML dashboard with metric cards, search, filters,
#                AppArmor/SELinux denials, eBPF programs, Desktop/Trash artifacts,
#                Cloud metadata, C2 Tunnels, Developer ecosystem, and threat alerts.
# Author: Bellk0ruh
# License: BSD 3-Clause
# ==============================================================================

set -uo pipefail

EVIDENCE_PATH="${1:-}"
OUTPUT_HTML="${2:-}"

# Automatically resolve the most recent DFIR folder if none specified
if [ -z "$EVIDENCE_PATH" ]; then
    EVIDENCE_PATH=$(ls -td DFIR-* 2>/dev/null | head -n 1 || echo "")
fi

if [ -z "$EVIDENCE_PATH" ] || [ ! -d "$EVIDENCE_PATH" ]; then
    echo "Usage: $0 [DFIR_Evidence_Folder] [Output_Report.html]" >&2
    exit 1
fi

HOSTNAME_VAL="Unknown-Host"
if [ -f "${EVIDENCE_PATH}/manifest.json" ]; then
    HOSTNAME_VAL=$(grep -oP '"hostname":\s*"\K[^"]+' "${EVIDENCE_PATH}/manifest.json" 2>/dev/null || echo "Unknown-Host")
fi

TIMESTAMP_VAL=$(date +"%Y%m%d_%H%M%S")
[ -z "$OUTPUT_HTML" ] && OUTPUT_HTML="${EVIDENCE_PATH}/DFIR-Report-${HOSTNAME_VAL}-${TIMESTAMP_VAL}.html"

CSV_DIR="${EVIDENCE_PATH}/CSV_Results"

echo "Generating standalone HTML forensic report..."
echo "Source Directory: ${EVIDENCE_PATH}"
echo "Output Report   : ${OUTPUT_HTML}"

# Metric counts
proc_count=$( [ -f "${CSV_DIR}/Processes.csv" ] && tail -n +2 "${CSV_DIR}/Processes.csv" | wc -l || echo "0" )
sock_count=$( [ -f "${CSV_DIR}/OpenSockets.csv" ] && tail -n +2 "${CSV_DIR}/OpenSockets.csv" | wc -l || echo "0" )
pers_count=$( [ -f "${CSV_DIR}/PersistenceSummary.csv" ] && tail -n +2 "${CSV_DIR}/PersistenceSummary.csv" | wc -l || echo "0" )
user_count=$( [ -f "${CSV_DIR}/LocalUsers.csv" ] && tail -n +2 "${CSV_DIR}/LocalUsers.csv" | wc -l || echo "0" )
suid_count=$( [ -f "${CSV_DIR}/SUIDBinaries.csv" ] && tail -n +2 "${CSV_DIR}/SUIDBinaries.csv" | wc -l || echo "0" )
ai_count=$( [ -f "${CSV_DIR}/AIToolsDetected.csv" ] && tail -n +2 "${CSV_DIR}/AIToolsDetected.csv" | wc -l || echo "0" )
device_count=$( [ -f "${CSV_DIR}/ConnectedDevices.csv" ] && tail -n +2 "${CSV_DIR}/ConnectedDevices.csv" | wc -l || echo "0" )
container_count=$( [ -f "${CSV_DIR}/Containers.csv" ] && tail -n +2 "${CSV_DIR}/Containers.csv" | wc -l || echo "0" )
tunnel_count=$( [ -f "${CSV_DIR}/TunnelingArtifacts.csv" ] && tail -n +2 "${CSV_DIR}/TunnelingArtifacts.csv" | wc -l || echo "0" )
ebpf_count=$( [ -f "${CSV_DIR}/EBPFPrograms.csv" ] && tail -n +2 "${CSV_DIR}/EBPFPrograms.csv" | wc -l || echo "0" )
dev_count=$( [ -f "${CSV_DIR}/DeveloperEcosystem.csv" ] && tail -n +2 "${CSV_DIR}/DeveloperEcosystem.csv" | wc -l || echo "0" )

# Suspicious indicator counts
deleted_exe_count=$( [ -f "${CSV_DIR}/DeletedRunningBinaries.csv" ] && tail -n +2 "${CSV_DIR}/DeletedRunningBinaries.csv" | wc -l || echo "0" )
memfd_count=$( [ -f "${CSV_DIR}/MemfdExecutions.csv" ] && tail -n +2 "${CSV_DIR}/MemfdExecutions.csv" | wc -l || echo "0" )
gtfo_count=$( [ -f "${CSV_DIR}/SUIDBinaries.csv" ] && grep -c ',"True"' "${CSV_DIR}/SUIDBinaries.csv" || echo "0" )
susp_cmd_count=$( [ -f "${CSV_DIR}/CommandHistory.csv" ] && grep -c ',"True"' "${CSV_DIR}/CommandHistory.csv" || echo "0" )
aa_denial_count=$( [ -f "${CSV_DIR}/AppArmorDenials.csv" ] && tail -n +2 "${CSV_DIR}/AppArmorDenials.csv" | wc -l || echo "0" )
se_denial_count=$( [ -f "${CSV_DIR}/SELinuxDenials.csv" ] && tail -n +2 "${CSV_DIR}/SELinuxDenials.csv" | wc -l || echo "0" )
total_alerts=$((deleted_exe_count + memfd_count + gtfo_count + susp_cmd_count + aa_denial_count + se_denial_count))

# Helper function to convert CSV into filterable HTML table
csv_to_html_table() {
    local csv_file="$1"
    local table_id="$2"
    
    if [ ! -f "$csv_file" ] || [ "$(wc -l < "$csv_file")" -le 1 ]; then
        echo "<p class='no-data'>No data available for this section.</p>"
        return
    fi
    
    echo "<div class='table-responsive'>"
    echo "<table class='dfir-table' id='${table_id}'>"
    echo "<thead><tr>"
    
    # Table headers
    head -n 1 "$csv_file" | sed 's/\r//g' | awk -F',' '{
        for (i=1; i<=NF; i++) {
            gsub(/^"|"$/, "", $i);
            print "<th>" $i "</th>";
        }
    }'
    echo "</tr></thead><tbody>"
    
    # Table rows
    tail -n +2 "$csv_file" | head -n 500 | sed 's/\r//g' | while IFS= read -r row || [ -n "$row" ]; do
        echo "<tr>"
        # Parse CSV line respecting double quotes
        echo "$row" | awk -v FPAT='([^,]+)|(\"[^\"]+\")' '{
            for (i=1; i<=NF; i++) {
                val = $i;
                gsub(/^"|"$/, "", val);
                gsub(/</, "\\&lt;", val);
                gsub(/>/, "\\&gt;", val);
                
                # Highlighting suspicious values
                cls = "";
                if (val == "True" || val == "CRITICAL" || val == "HIGH" || val == "DENIED" || val == "UNAUTHENTICATED_PUBLIC_EXPOSURE" || val == "RUNNING" || val == "SUSPICIOUS_PROBE_TYPE" || val == "CODE_EXECUTION_HOOK") {
                    cls = "badge-danger";
                } else if (val == "MEDIUM" || val == "DETECTED" || val == "WARNING" || val == "CONFIG_FOUND" || val == "ACTIVE" || val == "AUTH_TOKEN_PRESENT") {
                    cls = "badge-warning";
                }
                
                if (cls != "") {
                    print "<td><span class=\"" cls "\">" val "</span></td>";
                } else {
                    print "<td>" val "</td>";
                }
            }
        }'
        echo "</tr>"
    done
    
    echo "</tbody></table></div>"
}

# ------------------------------------------------------------------------------
# Assemble HTML Document
# ------------------------------------------------------------------------------
cat <<EOF > "$OUTPUT_HTML"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DFIR Bash Forensic Report - ${HOSTNAME_VAL}</title>
    <style>
        :root {
            --bg-main: #0d1117;
            --bg-card: #161b22;
            --bg-hover: #21262d;
            --border-color: #30363d;
            --text-main: #c9d1d9;
            --text-muted: #8b949e;
            --accent-cyan: #58a6ff;
            --accent-green: #3fb950;
            --accent-yellow: #d29922;
            --accent-red: #f85149;
            --accent-purple: #bc8cff;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; }
        body { background-color: var(--bg-main); color: var(--text-main); line-height: 1.6; padding: 24px; }
        
        .header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 20px; border-bottom: 1px solid var(--border-color); margin-bottom: 24px; flex-wrap: wrap; gap: 15px; }
        .header h1 { font-size: 24px; color: #ffffff; display: flex; align-items: center; gap: 10px; }
        .header h1 span { color: var(--accent-cyan); }
        .header .meta { font-size: 13px; color: var(--text-muted); text-align: right; }
        
        /* Metric Cards Grid */
        .metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 14px; margin-bottom: 28px; }
        .card { background-color: var(--bg-card); border: 1px solid var(--border-color); border-radius: 8px; padding: 14px; display: flex; flex-direction: column; transition: transform 0.2s, border-color 0.2s; }
        .card:hover { transform: translateY(-2px); border-color: var(--accent-cyan); }
        .card .title { font-size: 11px; font-weight: 600; text-transform: uppercase; color: var(--text-muted); margin-bottom: 6px; }
        .card .value { font-size: 22px; font-weight: 700; color: #ffffff; }
        .card.alert-card .value { color: var(--accent-red); }
        
        /* Search & Filter Bar */
        .controls-bar { display: flex; gap: 15px; margin-bottom: 20px; flex-wrap: wrap; }
        .search-box { flex: 1; min-width: 250px; background-color: var(--bg-card); border: 1px solid var(--border-color); border-radius: 6px; padding: 10px 14px; color: #ffffff; font-size: 14px; outline: none; }
        .search-box:focus { border-color: var(--accent-cyan); }
        
        /* Navigation Tabs */
        .tabs { display: flex; gap: 6px; border-bottom: 1px solid var(--border-color); margin-bottom: 24px; overflow-x: auto; padding-bottom: 4px; }
        .tab-btn { background: none; border: none; padding: 8px 12px; color: var(--text-muted); font-size: 12px; font-weight: 600; cursor: pointer; border-radius: 6px; transition: all 0.2s; white-space: nowrap; }
        .tab-btn:hover { background-color: var(--bg-hover); color: var(--text-main); }
        .tab-btn.active { background-color: var(--bg-hover); color: var(--accent-cyan); border-bottom: 2px solid var(--accent-cyan); }
        
        /* Tab Content */
        .tab-pane { display: none; }
        .tab-pane.active { display: block; animation: fadeIn 0.3s ease; }
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
        
        /* Tables */
        .table-responsive { overflow-x: auto; background-color: var(--bg-card); border: 1px solid var(--border-color); border-radius: 8px; margin-bottom: 24px; }
        .dfir-table { width: 100%; border-collapse: collapse; text-align: left; font-size: 13px; }
        .dfir-table th { background-color: #1c2128; color: var(--text-muted); padding: 12px 14px; font-weight: 600; border-bottom: 1px solid var(--border-color); }
        .dfir-table td { padding: 10px 14px; border-bottom: 1px solid var(--border-color); color: var(--text-main); word-break: break-all; }
        .dfir-table tr:hover { background-color: var(--bg-hover); }
        
        /* Badges */
        .badge-danger { background-color: rgba(248, 81, 73, 0.15); color: var(--accent-red); padding: 3px 8px; border-radius: 12px; font-weight: 600; font-size: 11px; border: 1px solid rgba(248, 81, 73, 0.4); }
        .badge-warning { background-color: rgba(210, 153, 34, 0.15); color: var(--accent-yellow); padding: 3px 8px; border-radius: 12px; font-weight: 600; font-size: 11px; border: 1px solid rgba(210, 153, 34, 0.4); }
        .badge-info { background-color: rgba(88, 166, 255, 0.15); color: var(--accent-cyan); padding: 3px 8px; border-radius: 12px; font-weight: 600; font-size: 11px; }
        
        .section-title { font-size: 18px; color: #ffffff; margin-bottom: 14px; display: flex; align-items: center; gap: 8px; }
        .no-data { padding: 20px; color: var(--text-muted); font-style: italic; text-align: center; }
        
        /* Footer */
        .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid var(--border-color); text-align: center; font-size: 12px; color: var(--text-muted); }
    </style>
</head>
<body>

    <div class="header">
        <div>
            <h1><span>⚡ DFIR Bash</span> Incident Response Report</h1>
            <p style="color: var(--text-muted); font-size: 14px; margin-top: 4px;">Host: <strong>${HOSTNAME_VAL}</strong> | Automated Forensics Dashboard</p>
        </div>
        <div class="meta">
            <div>Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")</div>
            <div>Evidence Dir: ${EVIDENCE_PATH}</div>
        </div>
    </div>

    <!-- Metrics Cards -->
    <div class="metrics-grid">
        <div class="card alert-card">
            <div class="title">Alerts & Anomalies</div>
            <div class="value">${total_alerts}</div>
        </div>
        <div class="card">
            <div class="title">Active Processes</div>
            <div class="value">${proc_count}</div>
        </div>
        <div class="card">
            <div class="title">Sockets & Ports</div>
            <div class="value">${sock_count}</div>
        </div>
        <div class="card">
            <div class="title">Persistence Items</div>
            <div class="value">${pers_count}</div>
        </div>
        <div class="card">
            <div class="title">eBPF Filters</div>
            <div class="value">${ebpf_count}</div>
        </div>
        <div class="card">
            <div class="title">Containers</div>
            <div class="value">${container_count}</div>
        </div>
        <div class="card">
            <div class="title">Tunnels / VPNs</div>
            <div class="value">${tunnel_count}</div>
        </div>
        <div class="card">
            <div class="title">Dev / Secrets</div>
            <div class="value">${dev_count}</div>
        </div>
    </div>

    <!-- Controls -->
    <div class="controls-bar">
        <input type="text" id="globalSearch" class="search-box" placeholder="🔍 Search across all tables (PID, IP, Command, User, Hash, Denials, eBPF)..." onkeyup="filterTables()">
    </div>

    <!-- Tabs Navigation -->
    <div class="tabs">
        <button class="tab-btn active" onclick="switchTab(event, 'tab-alerts')">⚡ Detections & MITRE (${total_alerts})</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-ebpf')">🔬 eBPF & Stealth</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-mac')">🛡️ AppArmor & SELinux</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-proc')">🖥️ Processes (${proc_count})</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-net')">🌐 Network (${sock_count})</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-tunnels')">🔗 VPN & C2 Tunnels</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-cloud')">☁️ Cloud & Web/DB</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-dev')">📦 Dev & Supply Chain</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-desktop')">💻 Desktop & Trash</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-pers')">🔄 Persistence (${pers_count})</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-hardware')">🔌 Devices & Containers</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-users')">👤 Users (${user_count})</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-files')">📁 SUID & Staging (${suid_count})</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-ai')">🤖 AI Artifacts (${ai_count})</button>
        <button class="tab-btn" onclick="switchTab(event, 'tab-logs')">📜 Security Events</button>
    </div>

    <!-- Tab 1: Alerts & Rootkits -->
    <div id="tab-alerts" class="tab-pane active">
        <h2 class="section-title">Threat Indicators & Rootkit Signals</h2>
        $(csv_to_html_table "${CSV_DIR}/RootkitIndicators.csv" "tbl-rootkits")
        
        <h2 class="section-title" style="margin-top: 24px;">Deleted Running Binaries in Memory (/proc/PID/exe)</h2>
        $(csv_to_html_table "${CSV_DIR}/DeletedRunningBinaries.csv" "tbl-del-bin")
        
        <h2 class="section-title" style="margin-top: 24px;">Anonymous In-Memory Executions (memfd_create)</h2>
        $(csv_to_html_table "${CSV_DIR}/MemfdExecutions.csv" "tbl-memfd")
        
        <h2 class="section-title" style="margin-top: 24px;">Suspicious Historical Commands Detected</h2>
        $(csv_to_html_table "${CSV_DIR}/CommandHistory.csv" "tbl-cmd-susp")
    </div>

    <!-- Tab: eBPF & Stealth -->
    <div id="tab-ebpf" class="tab-pane">
        <h2 class="section-title">Loaded eBPF Programs, Socket Filters & Probes</h2>
        $(csv_to_html_table "${CSV_DIR}/EBPFPrograms.csv" "tbl-ebpf")
    </div>

    <!-- Tab: AppArmor & SELinux -->
    <div id="tab-mac" class="tab-pane">
        <h2 class="section-title">Mandatory Access Control (MAC) Subsystems Status</h2>
        $(csv_to_html_table "${CSV_DIR}/MACSubsystems.csv" "tbl-mac-status")
        
        <h2 class="section-title" style="margin-top: 24px;">AppArmor Denials & Audit Violations</h2>
        $(csv_to_html_table "${CSV_DIR}/AppArmorDenials.csv" "tbl-aa-denials")
        
        <h2 class="section-title" style="margin-top: 24px;">SELinux AVC Denials (type=AVC)</h2>
        $(csv_to_html_table "${CSV_DIR}/SELinuxDenials.csv" "tbl-se-denials")
    </div>

    <!-- Tab 2: Processes -->
    <div id="tab-proc" class="tab-pane">
        <h2 class="section-title">Process Table & Execution Tree</h2>
        $(csv_to_html_table "${CSV_DIR}/Processes.csv" "tbl-processes")
    </div>

    <!-- Tab 3: Network -->
    <div id="tab-net" class="tab-pane">
        <h2 class="section-title">Sockets and Active Connections</h2>
        $(csv_to_html_table "${CSV_DIR}/OpenSockets.csv" "tbl-sockets")
        
        <h2 class="section-title" style="margin-top: 24px;">Network Interfaces</h2>
        $(csv_to_html_table "${CSV_DIR}/NetworkInterfaces.csv" "tbl-interfaces")
        
        <h2 class="section-title" style="margin-top: 24px;">ARP Cache & Neighbors</h2>
        $(csv_to_html_table "${CSV_DIR}/ARPTable.csv" "tbl-arp")
    </div>

    <!-- Tab: Tunnels & VPNs -->
    <div id="tab-tunnels" class="tab-pane">
        <h2 class="section-title">Encrypted Tunnels, VPNs & Reverse Proxies (WireGuard, Tailscale, Ngrok, Chisel)</h2>
        $(csv_to_html_table "${CSV_DIR}/TunnelingArtifacts.csv" "tbl-tunnels")
    </div>

    <!-- Tab: Cloud & Web/DB -->
    <div id="tab-cloud" class="tab-pane">
        <h2 class="section-title">Cloud Instance Identity & IAM Metadata (AWS, Azure, GCP)</h2>
        $(csv_to_html_table "${CSV_DIR}/CloudMetadata.csv" "tbl-cloud")
        
        <h2 class="section-title" style="margin-top: 24px;">Web & Database Servers (Nginx, Apache, Redis, MySQL, PostgreSQL)</h2>
        $(csv_to_html_table "${CSV_DIR}/WebAndDatabaseServers.csv" "tbl-web-db")
    </div>

    <!-- Tab: Dev & Supply Chain -->
    <div id="tab-dev" class="tab-pane">
        <h2 class="section-title">Developer Secrets, Package Managers & Git Hooks</h2>
        $(csv_to_html_table "${CSV_DIR}/DeveloperEcosystem.csv" "tbl-dev-eco")
    </div>

    <!-- Tab: Desktop & Trash -->
    <div id="tab-desktop" class="tab-pane">
        <h2 class="section-title">Deleted Files in Linux Trash (~/.local/share/Trash)</h2>
        $(csv_to_html_table "${CSV_DIR}/TrashArtifacts.csv" "tbl-trash")
        
        <h2 class="section-title" style="margin-top: 24px;">Recently Opened Files (recently-used.xbel)</h2>
        $(csv_to_html_table "${CSV_DIR}/RecentFiles.csv" "tbl-recent")
    </div>

    <!-- Tab 4: Persistence -->
    <div id="tab-pers" class="tab-pane">
        <h2 class="section-title">Persistence Mechanisms Summary</h2>
        $(csv_to_html_table "${CSV_DIR}/PersistenceSummary.csv" "tbl-persistence")
        
        <h2 class="section-title" style="margin-top: 24px;">Scheduled Tasks (Cron & Timers)</h2>
        $(csv_to_html_table "${CSV_DIR}/ScheduledTasks.csv" "tbl-cron")
        
        <h2 class="section-title" style="margin-top: 24px;">Shell Startup Hooks (/etc/profile.d, .bashrc)</h2>
        $(csv_to_html_table "${CSV_DIR}/ShellHooks.csv" "tbl-shellhooks")
    </div>

    <!-- Tab: Devices & Containers -->
    <div id="tab-hardware" class="tab-pane">
        <h2 class="section-title">Connected Devices (USB / Hardware)</h2>
        $(csv_to_html_table "${CSV_DIR}/ConnectedDevices.csv" "tbl-connected-devices")
        
        <h2 class="section-title" style="margin-top: 24px;">Storage Mount Points & Filesystems</h2>
        $(csv_to_html_table "${CSV_DIR}/MountPoints.csv" "tbl-mounts")
        
        <h2 class="section-title" style="margin-top: 24px;">Active & Dormant Containers (Docker / Podman)</h2>
        $(csv_to_html_table "${CSV_DIR}/Containers.csv" "tbl-containers")
        
        <h2 class="section-title" style="margin-top: 24px;">System Crash & Core Dumps (coredumpctl)</h2>
        $(csv_to_html_table "${CSV_DIR}/SystemCoredumps.csv" "tbl-coredumps")
    </div>

    <!-- Tab 5: Users -->
    <div id="tab-users" class="tab-pane">
        <h2 class="section-title">Local User Accounts</h2>
        $(csv_to_html_table "${CSV_DIR}/LocalUsers.csv" "tbl-users")
        
        <h2 class="section-title" style="margin-top: 24px;">Active Sessions</h2>
        $(csv_to_html_table "${CSV_DIR}/ActiveSessions.csv" "tbl-sessions")
        
        <h2 class="section-title" style="margin-top: 24px;">Authorized SSH Keys (authorized_keys)</h2>
        $(csv_to_html_table "${CSV_DIR}/SSHAuthorizedKeys.csv" "tbl-sshkeys")
        
        <h2 class="section-title" style="margin-top: 24px;">Sudoers Privileges</h2>
        $(csv_to_html_table "${CSV_DIR}/SudoPrivileges.csv" "tbl-sudoers")
    </div>

    <!-- Tab 6: File System -->
    <div id="tab-files" class="tab-pane">
        <h2 class="section-title">SUID / SGID Binaries (GTFOBins Audit)</h2>
        $(csv_to_html_table "${CSV_DIR}/SUIDBinaries.csv" "tbl-suid")
        
        <h2 class="section-title" style="margin-top: 24px;">Extended Linux Capabilities (getcap)</h2>
        $(csv_to_html_table "${CSV_DIR}/FileCapabilities.csv" "tbl-caps")
        
        <h2 class="section-title" style="margin-top: 24px;">Staging Directory Files (/tmp, /dev/shm)</h2>
        $(csv_to_html_table "${CSV_DIR}/StagingFiles.csv" "tbl-staging")
    </div>

    <!-- Tab 7: AI & Dev Tools -->
    <div id="tab-ai" class="tab-pane">
        <h2 class="section-title">Artificial Intelligence & Local LLM Servers</h2>
        $(csv_to_html_table "${CSV_DIR}/AIToolsDetected.csv" "tbl-ai-tools")
        
        <h2 class="section-title" style="margin-top: 24px;">AI Token & API Key Presence</h2>
        $(csv_to_html_table "${CSV_DIR}/AITokenPresence.csv" "tbl-ai-tokens")
        
        <h2 class="section-title" style="margin-top: 24px;">AI Prompt & Chat Histories</h2>
        $(csv_to_html_table "${CSV_DIR}/AIPromptHistories.csv" "tbl-ai-prompts")
    </div>

    <!-- Tab 8: Logs -->
    <div id="tab-logs" class="tab-pane">
        <h2 class="section-title">Extracted Security Events (Auth / Sudo / SSH)</h2>
        $(csv_to_html_table "${CSV_DIR}/SecurityEvents.csv" "tbl-sec-events")
    </div>

    <div class="footer">
        <p>Digital Forensics & Incident Response Report — DFIR Bash Suite by Bellk0ruh</p>
    </div>

    <script>
        function switchTab(evt, tabName) {
            var tabPanes = document.getElementsByClassName("tab-pane");
            for (var i = 0; i < tabPanes.length; i++) {
                tabPanes[i].classList.remove("active");
            }
            var tabBtns = document.getElementsByClassName("tab-btn");
            for (var i = 0; i < tabBtns.length; i++) {
                tabBtns[i].classList.remove("active");
            }
            document.getElementById(tabName).classList.add("active");
            evt.currentTarget.classList.add("active");
        }

        function filterTables() {
            var input = document.getElementById("globalSearch");
            var filter = input.value.toUpperCase();
            var activePane = document.querySelector(".tab-pane.active");
            if (!activePane) return;
            
            var tables = activePane.getElementsByTagName("table");
            for (var t = 0; t < tables.length; t++) {
                var tr = tables[t].getElementsByTagName("tr");
                for (var i = 1; i < tr.length; i++) {
                    var rowText = tr[i].textContent || tr[i].innerText;
                    if (rowText.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
</body>
</html>
EOF

echo "HTML report generated successfully at: ${OUTPUT_HTML}"
